### PR TITLE
Switched to the more performant System.Threading.Lock on .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
I don't think this approach is needed for CSnakes. None of the new `Lock` features are needed here.

Just declaring a `class Lock;` for pre .NET 9 TFMs is more appropriate and doesn't introduce servicing issues with other libraries.

**Comment by AaronRobinsonMSFT** [comment]
@MarkCiliaVincenti Would you be willing to update this PR to just go with the simpler approach below?

```csharp
#if NET9_0_OR_GREATER
global using Lock = System.Threading.Lock;
#else
global using Lock = object;
#endif
```

**Comment by tonybaloney** [comment]
Thanks for the PR. Closing in favour of #289

**Comment by MarkCiliaVincenti** [comment]
@tonybaloney  A new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.

**Comment by AaronRobinsonMSFT** [comment]
> @tonybaloney A new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.

@MarkCiliaVincenti Something to consider with 3rd party source generators is that of servicing. By relying on a 3rd party library this library must monitor and trust that Backport.System.Threading.Lock will announce and manage servicing events. When one occurs this library then needs to respond and inform all its consumers. From my perspective consuming source generators that don't have a robust CVE process is a non-starter.

Eventhough CSnakes is an experimental library, it is being built to be consumed by products that have a fairly high degree of scrutiny on this front. I'm not sure it is appropriate to adopt any source generator outside of the built-in .NET product in this case.

**Pull request closed without merging**
