### PR TITLE
Use `System.Threading.Lock` on .NET 9.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Alternative proposal to https://github.com/tonybaloney/CSnakes/pull/263.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Works, but please refer to https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock?tab=readme-ov-file#why-not-keep-it-simple

**Comment by aaronpowell** [comment]
I'm inclined to go with this approach rather than bringing in an external dependency like #263 does primarily because we're not likely to leverage the methods that the .NET 9 `Lock` type introduces - unless you can see areas in which we could benefit from it @MarkCiliaVincenti so I can better understand what limitations we might have in our current design.

**Comment by MarkCiliaVincenti** [comment]
Nothing in particular, as long as you're aware. Should you need you can then easily switch to the version that uses the backport.

**Comment by AaronRobinsonMSFT** [comment]
@aaronpowell or @tonybaloney Either of you want to sign off on this so we can get it in?

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
